language: csharp
sudo: true
mono: none
dotnet: 2.2
dist: xenial
branches:
  only:
    - master
install:
  # Install Proxy
  - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_11.x" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - sudo apt-get install -y npm
  - sudo npm i -g n --force -g --registry=https://registry.npm.taobao.org
  - sudo n latest
  - sudo npm install o_o -g --registry=https://registry.npm.taobao.org
  # Install dotnet codecov tool and restore
  - dotnet tool install --global altcover.visualizer
  - cd aliyun-net-sdk-core.Tests/ && dotnet add package AltCover && cd ../
script:
  # Start Proxy
  - sudo o_o &
  # Dotnet test
  - dotnet build aliyun-net-sdk-core.netstandard20.sln
  - if [[ $ACCESS_KEY_ID == "" ]]; then dotnet test aliyun-net-sdk-core.Tests /p:AltCover=true; else dotnet test aliyun-net-sdk-core.netstandard20.sln /p:AltCover=true; fi
after_success:
  - cd aliyun-net-sdk-core.Tests/
  - bash <(curl -s https://codecov.io/bash) -c -F unittest
